---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
file_log_structure: "'file' String, 'hosts' String, 'message' String, 'timestamp' DateTime"